spring:
  application:
    name: antelope-service-order
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
server:
  port: 8901
logging:
  level:
    org.springframework: info
    com.antelope: debug

eureka:
  instance:
#    hostname: antelope-gateway
#    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: 192.168.202.144
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka